services:
  a02-backend:
    container_name: a02-devs-backend
    build:
      context: ./devs-backend
      dockerfile: Dockerfile
    image: a02-devs-backend
    restart: always
    ports:
      - 8092:8092
    environment:
      - JWT_SECRET=${A02_JWT_SECRET}
      - SERVER_PORT=${A02_SERVER_PORT}
      - SERVER_PATH=${A02_SERVER_PATH}
  a02-frontend:
    container_name: a02-devs-frontend
    build:
      context: ./devs-react-app
      dockerfile: Dockerfile
      args:
        - REACT_APP_BASE_PATH=${A02_REACT_APP_BASE_PATH}
    image: a02-devs-frontend
    restart: always
    ports:
      - 3002:80
    depends_on:
      - a02-backend
